### PR TITLE
`using` statement

### PR DESCRIPTION
**Pull request by EQt**
Now you can load Julia Packages in Python

### CODE REVIEW

**Comment by benmoran** [comment]
Nice, thank you!  Did you use a particular version of PyCall?  I submitted a patch to PyCall to make it work with PyJulia on Linux, which got reverted on master in https://github.com/stevengj/PyCall.jl/pull/230 - but perhaps that doesn't affect you on Windows.

**Comment by EQt** [comment]
I used the default version of JuliaLang/METADATA.jl which is currently v1.4.0 (master branch).
The error is with Python 2.7 (64 Bit) on Windows. It happens during the very first call to jl_init, so it has nothing to do with PyCall. Within libjulia there seems to be an uninitialized pointer as the error is:

```
python -m unittest discover

Please submit a bug report with steps to reproduce this fault, and any error messages that follow (in their entirety). Thanks.
Exception: EXCEPTION_ACCESS_VIOLATION at 0x0 -- unknown function (ip: 0000000000000000)
unknown function (ip: 0000000000000000)
JULIA_HOME = C:\projects\julia\bin,  libjulia_path = C:\projects\julia\bin\libjulia.dll
calling jl_init(C:\projects\julia\bin)
Command exited with code 1
```

The error message comes from [src/signals-win.c](https://github.com/JuliaLang/julia/search?utf8=%E2%9C%93&q=EXCEPTION_ACCESS_VIOLATION).

Maybe the error is due to libpython27. Don't know how to find out. Any idea?

**Comment by EQt** [comment]
https://github.com/JuliaLang/julia/issues/13570 might be the reason that it fails on windows with Python-27...

**Comment by benmoran** [comment]
I'm not sure about Windows - don't have any boxes to try it on except for Appveyor.

I see that the Travis CI build is working on Linux with Python 2.7.9, but on my Ubuntu 14.04 system Python 2.7.6 using the most recent 1.4.0 release of PyCall it still fails:

  InitError(:PyCall,PyError (:PyCapsule_Import) <type 'exceptions.ImportError'>
  ImportError('PyCapsule_Import could not import module "datetime"',)

I think this is because the Ubuntu system Python is statically linked.  The Python 2.7.9 in Travis must be built differently.  Using the v1.3.0 tag of PyCall works around this for me.

Thanks for your work, @EQt !

**Pull request merged**
